### ISSUE TITLE
Possibly merge with other Turn Marker

### ISSUE THREAD

**Issue by Zamrod** [kckaiwei/TurnMarker-alt#17]
Kreals has been updating a version of Turn Marker  here: https://github.com/Kreals/TurnMarker

It already has a bunch of fixes and feature enhancements in it. Perhaps it is worth merging the two.

**Comment by kckaiwei** [comment]
I'll reach out to him. I see he's done a overhaul into OO which is a major change, but I don't think he's fixed the 2 major bugs + the additional features. I'd be happy to get him onto the same project, since there's been a lot of other small fixes he's made that I didn't even know existed (no existing issues in OG repo)

**Comment by kckaiwei** [comment]
Contact has been made, closing this ticket.
