### ISSUE TITLE
Support Foundry 0.8.x

### ISSUE THREAD

**Issue by illandril** [kckaiwei/TurnMarker-alt#64]
TurnMarker doesn't work in Foundry 0.8.5.

I did spend a little time to see if I could quickly update it, but it looks like it might end up being a little complicated.

If you want it as a starting point, here's my initial work towards this:
https://github.com/illandril/TurnMarker-alt/tree/08x-test

This manages to fix a lot of the errors and deprecation warnings... unfortunately, the turn marker doesn't update at all so I either missed something or broke something along the way, and I don't have the time to continue this effort.

**Comment by kckaiwei** [comment]
I suspect it doesn't work on 0.8.0+ at all. I haven't looked at anything past the release branch to be honest. I see in the notes for 0.8.0:

`As a consequence of the new standardized Document model, objects which are placed on the canvas (Tokens, Tiles, etc...) now have a separation between the classes which are responsible for how the object is rendered and the classes which define and manage their underlying data structure.`

It's likely everything will be broken. I'll start taking a look at the 0.8 versions since it sounds like whenever the release branch gets there, I'll have a lot to do anyways. Thanks for bringing it to my attention.

**Comment by apoapostolov** [comment]
Meanwhile Next Up works, except the icon mode for starting location. But I would much prefer if TurnMarker was given a lease of life in 0.8.x

**Comment by kckaiwei** [comment]
@illandril @apoapostolov Just put out an update/fix for it. As far as I can see testing it, TurnMarker seems to work. No doubt it will probably be unstable since I haven't had too much time to mess with it in an attempt to get it out quickly. 

Please let me know if you run across any bugs, since I have no doubt there will be some. 

I've only tested it on 0.8.6 since that's the actual release version, and probably won't look to make things like 0.8.0 work since it's likely everyone will be on 0.8.6+ soon.
